name: Report LP issue on GitHub
on:
  push:
    paths:
      - '.github/workflows/track-lp-issues.yaml'
  schedule:
    - cron: '0 20 * * *'

jobs:
  add-lp-issues:
    name: Port LP issues into GitHub bug tracker
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v2.3.4
      - name: Install Python 3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install launchpadlib
      - name: Mirror GitHub bugs from Launchpad
        id: getlpbugs
        run: |
          python .github/lpbugtracker.py

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
